---
title: "Propose a session"
---


The department of economic history together with the Swedish Economic History Society and the Scandinavian Society for Economic and Social History is organizing the 15th Swedish economic history meeting in Lund on the 27th, 28th and 29 of September 2023. The meeting will be combined with the fourth Annual Conference of the Scandinavian Society for Economic and Social History.

We are now inviting session proposals. Any themes are welcome, but we would like to encourage session organisers to consider themes that may facilitate the formation of new collaborations and networks. Please, note that proposing a session does not necessitate that you must chair the session. The deadline for session proposals is **the 15th of February 2023.**


<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfefHFCbwMOgT1_GZgVOFlJlO5Wvz-wCqlJtNbC-OZG9b6tPw/viewform?embedded=true" width="800" height="1200" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

---

If you have any questions, please feel free to [contact us here {{< fa paper-plane >}}]()


