---
title: "Celebrate New Scholarship: Book Launch"
subtitle: "Thursday the 28th of September at AF Borgen"
---

The book launch session aims provide an excellent opportunity for authors to showcase their latest work, discuss their research, and engage with other scholars in the field.

The books being presented are:

## Colonial Ports, Global Trade, and the Roots of the American Revolution

**Jeremy Land**

This book takes a long-run view of the global maritime trade of Boston, New York, and Philadelphia from 1700 to American Independence in 1776. Land argues that the three cities developed large, global networks of maritime commerce and exchange that created tension between merchants and the British Empire which sought to enforce mercantilist policies to constrain American trade to within the British Empire. Colonial merchants created and then expanded their mercantile networks well beyond the confines of the British Empire. This trans-imperial trade (often considered smuggling by British authorities) formed the roots of what became known as the American Revolution.

## Creating the Cape Colony: The Political Economy of Settler Colonization

**Erik Green**

This open access book offers a detailed study of the foundation and expansion of the Dutch Cape Colony to ask why certain regions in the global south became European settler societies from the 16th century onwards.

Examining the different factors that led to the creation of the Cape Colony, Erik Green reveals it was a gradual process, made up of ad hoc decisions, in which the agency of indigenous peoples played an important role. He identifies the drivers behind settler expansion, explores the effect of inequality on long-term economic development and examines the relationship between settlers and the colonial authorities, asserting that they should not be treated as one homogenous group with shared economic interests. Assessing specific characteristics of the Cape Colony, such as the proposition it was a slavery economy, and comparing key insights of this study with the historiography of other settler colonies, Creating the Cape Colony demonstrates the need to revise our understanding of how settler economies operated, and to rethink the long-term legacies of settler colonialism.

## Den industrielle revolusjon: Kapitalisme, industri og teknologi

**Kristine Bruland**

The book, Den industrielle revolusjon. Kapitalisme, industri og teknologi, was published in August, 2022.
It challenges the traditional view of the Industrial Revolution as a short event (1760-1830), which was British, and was driven by a small number of technologies (textiles, steam and the factory). I argue that it was a transition that took a very long time (from around 14/1500), that it was not British but global, and that it was not based on a small set of innovations, but a large number, spread across all economic activity. This leads me to seek an explanation of the industrial transition which was equally wide, and I argue that this was the transition to capitalism - first in agriculture, then manufacture and industry. I identify three drivers: product competition, control of the production process and the development of a capital goods industry.

## En miljard till svensk musik: Riksdaler och kronor i tjänst hos Musikaliska Akademien under 250 år

**Staffan Albinsson**

Kungliga Musikaliska Akademien grundades 1771. Dess barndom var svår trots att det var välbärgade individer ur Stockholms överklass som valdes som medlemmar. En av akademiens legendariska sekreterare konstaterade 25 år senare att akademiens primära syfte då verkar ha varit att anordna ett eget lotteri och att styrelsens roll var att avnjuta ”de goda Måltider, som wankades hos Gumman Noach eller Simsons hwid hwarje Lotteri-Dragning”. Så småningom kom kungliga donationer. Riksdagen började bidra med årliga anslag. Från mitten av 1800-talet har en stor mängd donationer kommit från privatpersoner. Akademien har därför nu att förvalta donationsfonder om sammanlagt runt en miljard kronor. Fondernas urkunder anger de ändamål som akademien måste rätta sig efter.


Under runt halvtannat sekel var undervisningen vid konservatoriet akademiens viktigaste uppgift. Därtill kom att bygga upp ett musikbibliotek och senare även ett musikmuseum och ett musikhistoriskt arkiv. Under senare delen av 1900-talet blev dessa fyra verksamheter överförda till statliga myndigheter. Musikaliska Akademien har sedan 1981 ägnat sig åt att föra musiklivets talan i det offentliga, driva angelägna utvecklingsprojekt och fördela medel ur cirka 150 donationsstiftelser.


Ekonomihistorikern Staffan Albinsson beskriver här Kungliga Musikaliska Akademiens 250 år
med fokus i hur dess verksamheter utvecklats med hjälp av riksdagens och privatpersoners
finansiering. 

